script:
  - |
    set -eo pipefail

    mkdir -p BUILD
    echo '*' > BUILD/.mbedignore
    cat > fake_main.c <<MAIN
    #include "mbed_toolchain.h"
    MBED_WEAK void main(void) {}
    MAIN

    function compile {
        if [ "$1" != "NO" ]
        then
            PYTHONPATH=mbed-os python mbed-os/tools/make.py -t GCC_ARM -m ${1:-ARCH_PRO} --source=. --build=BUILD/${1:-ARCH_PRO}/GCC_ARM | sed '/\(error\|warning\)/I!d'
        fi
    }
     
    for f in $(find -name mbed-os -prune -o -name '*.md' -print)
    do
        # compile c++ snippets
        for l in $(sed -n '/``` *\(cpp\|c++\)\($\| \+\)/I=' $f)
        do
            echo "Validating cpp $f:$l ..."
            sed -n $l',/```/{/```/d;p}' $f > main.cpp
            compile "$(sed -n $l's/ *``` *\(cpp\|c++\)\($\| \+\)//Ip' $f)"
            rm main.cpp
        done
        
        # compile c snippets
        for l in $(sed -n '/``` *c\($\| \+\)/I=' $f)
        do
            echo "Validating c $f:$l ..."
            sed -n $l',/```/{/```/d;p}' $f > main.c
            compile "$(sed -n $l's/ *``` *c\($\| \+\)//Ip' $f)"
            rm main.c
        done

        # validate json snippets
        for l in $(sed -n '/``` *json\($\| \+\)/I=' $f)
        do
            echo "Validating json $f:$l ..."
            sed -n $l',/```/{/```/d;p}' $f > main.json
            if [ "$(sed -n $l's/ *``` *json\($\| \+\)//Ip' $f)" != "NO" ]
            then
                if sed -n '/ *"/q0;/ *[^ ]/q1' main.json
                then
                    (echo "{" ; cat main.json ; echo "}") | python -m json.tool > /dev/null
                else
                    cat main.json | python -m json.tool > /dev/null
                fi
            fi
            rm main.json
        done
    done

install:
      # Get arm-none-eabi-gcc
    - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
    - sudo apt-get update -qq
    - sudo apt-get install -qq gcc-arm-none-eabi --force-yes
      # Get dependencies
    - git clone https://github.com/armmbed/mbed-os.git
      # Install python dependencies
    - pip install --user -r mbed-os/requirements.txt
