script:
    - |
      set -eu

      function compile {
          PYTHONPATH=mbed-os python mbed-os/tools/make.py -t GCC_ARM -m K64F \
              --source=. --build=BUILD/K64F/GCC_ARM
      }

      for f in $(find -name '*.md')
      do
          # find all c++ snippets and compile
          for l in $(sed -n '/``` *\(cpp\|c++\)\>/=' $f)
          do
              sed -n $l',/```/{/```/d;p}' $f > main.cpp
              compile
              rm main.cpp
          done

          # find all c snippets and compile
          for l in $(sed -n '/``` *c\>/=' $f)
          do
              sed -n $l',/```/{/```/d;p}' $f > main.c
              compile
              rm main.c
          done
      done
    set -eu
    set -o pipefail

    mkdir -p BUILD
    echo '*' > BUILD/.mbedignore
    cat > fake_main.c <<MAIN
    #include "mbed_toolchain.h"
    MBED_WEAK void main(void) {}
    MAIN

    function compile {
        if [ "$1" != "NO" ]
        then
            PYTHONPATH=mbed-os python mbed-os/tools/make.py -t GCC_ARM \
                -m ${1:-ARCH_PRO} --source=. \
                --build=BUILD/${1:-ARCH_PRO}/GCC_ARM \
                | sed '/\(error\|warning\)/I!d'
        fi
    }
     
    for f in $(find -name '*.md')
    do
        # compile c++ snippets
        for l in $(sed -n '/``` *\(cpp\|c++\)\($\| \+\)/I=' $f)
        do
            echo "Building $f:$l ..."
            sed -n $l',/```/{/```/d;p}' $f > main.cpp
            compile "$(sed -n $l's/ *``` *\(cpp\|c++\)\($\| \+\)//Ip' $f)"
            rm main.cpp
        done
        
        # compile c snippets
        for l in $(sed -n '/``` *c\($\| \+\)/I=' $f)
        do
            echo "Building $f:$l ..."
            sed -n $l',/```/{/```/d;p}' $f > main.c
            compile "$(sed -n $l's/ *``` *c\($\| \+\)//Ip' $f)"
            rm main.c
        done
    done

install:
      # Get arm-none-eabi-gcc
    - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
    - sudo apt-get update -qq
    - sudo apt-get install -qq gcc-arm-none-eabi --force-yes
      # Get dependencies
    - git clone https://github.com/armmbed/mbed-os.git
      # Install python dependencies
    - pip install -r mbed-os/requirements.txt
